var produtos = [
    {
        id: 1,
        img: 'img/iphones/iphone-SE.jpg',
        nome: 'iPhone SE',
        descrcao: 'teste',
        category: 'iphone',
        price: 4.299,
        quantity: 1,
    },
    {
        id: 2,
        img: 'img/iphones/iphone-13.jpg',
        nome: 'iPhone 13',
        descrcao: 'teste',
        category: 'iphone',
        price: 5.499,
        quantity: 1,
    },
    {
        id: 3,
        img: 'img/iphones/iphone-14.jpg',
        nome: 'iPhone 14',
        descrcao: 'teste',
        category: 'iphone',
        price: 5.999,
        quantity: 1,
    },
    {
        id: 4,
        img: 'img/iphones/iphone14plus.png',
        nome: 'iPhone 14 Plus',
        descrcao: 'teste',
        category: 'iphone',
        price: 6.499,
        quantity: 1,
    },
    {
        id: 5,
        img: 'img/iphones/iphone-15.jpg',
        nome: 'iPhone 15',
        descrcao: 'teste',
        category: 'iphone',
        price: 7.299,
        quantity: 1,
    },
    {
        id: 6,
        img: 'img/iphones/iphone15plus.png',
        nome: 'iPhone 15 Plus',
        descrcao: 'teste',
        category: 'iphone',
        price: 8.299,
        quantity: 1,
    },
    {
        id: 7,
        img: 'img/iphones/iphone-15-pro.jpg',
        nome: 'iPhone 15 Pro',
        descrcao: 'teste',
        category: 'iphone',
        price: 9.299,
        quantity: 1,
    },
    {
        id: 8,
        img: 'img/iphones/iphone15promax.png',
        nome: 'iPhone 15 Pro Max',
        descrcao: 'teste',
        category: 'iphone',
        price: 10.999,
        quantity: 1,
    },
]

export { produtos };