var produtos = [
    {
        id: 1,
        img: 'img/produtos/iphone-SE.webp',
        nome: 'iPhone SE',
        descrcao: 'teste',
        category: 'iphone',
        price: 4299,
        quantity: 1,
    },
    {
        id: 2,
        img: 'img/produtos/iphone-13.webp',
        nome: 'iPhone 13',
        descrcao: 'teste',
        category: 'iphone',
        price: 5499,
        quantity: 1,
    },
    {
        id: 3,
        img: 'img/produtos/iphone-14.webp',
        nome: 'iPhone 14',
        descrcao: 'teste',
        category: 'iphone',
        price: 5999,
        quantity: 1,
    },
    {
        id: 4,
        img: 'img/produtos/iphone14plus.webp',
        nome: 'iPhone 14 Plus',
        descrcao: 'teste',
        category: 'iphone',
        price: 6499,
        quantity: 1,
    },
    {
        id: 5,
        img: 'img/produtos/iphone-15.webp',
        nome: 'iPhone 15',
        descrcao: 'teste',
        category: 'iphone',
        price: 7299,
        quantity: 1,
    },
    {
        id: 6,
        img: 'img/produtos/iphone15plus.webp',
        nome: 'iPhone 15 Plus',
        descrcao: 'teste',
        category: 'iphone',
        price: 8299,
        quantity: 1,
    },
    {
        id: 7,
        img: 'img/produtos/iphone-15-pro.webp',
        nome: 'iPhone 15 Pro',
        descrcao: 'teste',
        category: 'iphone',
        price: 9299,
        quantity: 1,
    },
    {
        id: 8,
        img: 'img/produtos/iphone15promax.webp',
        nome: 'iPhone 15 Pro Max',
        descrcao: 'teste',
        category: 'iphone',
        price: 10999,
        quantity: 1,
    },
    {
        id: 9,
        img: 'img/produtos/ipad-card.webp',
        nome: 'ipad mini',
        descrcao: 'teste',
        category: 'ipad',
        price: 5999,
        quantity: 1,
    },
    {
        id: 10,
        img: 'img/produtos/ipad-9.webp',
        nome: 'iPadiPad (9ª geração)',
        descrcao: 'teste',
        category: 'ipad',
        price: 3799,
        quantity: 1,
    },
    {
        id: 11,
        img: 'img/produtos/ipad-10.webp',
        nome: 'iPadiPad (10ª geração)',
        descrcao: 'teste',
        category: 'ipad',
        price: 4999,
        quantity: 1,
    },
    {
        id: 12,
        img: 'img/produtos/ipad-air.webp',
        nome: 'iPad Air',
        descrcao: 'teste',
        category: 'ipad',
        price: 6999,
        quantity: 1,
    },
    {
        id: 13,
        img: 'img/produtos/ipad-pro.webp',
        nome: 'iPad Pro',
        descrcao: 'teste',
        category: 'ipad',
        price: 9799,
        quantity: 1,
    },
    {
        id: 14,
        img: 'img/produtos/pro-display.webp',
        nome: 'Pro Display XDR',
        descrcao: 'teste',
        category: 'Mac',
        price: 44999,
        quantity: 1,
    },
    {
        id: 15,
        img: 'img/produtos/mac-pro.webp',
        nome: 'Mac Pro',
        descrcao: 'teste',
        category: 'Mac',
        price: 74999,
        quantity: 1,
    },
    {
        id: 16,
        img: 'img/produtos/studio-display.webp',
        nome: 'Studio Display',
        descrcao: 'teste',
        category: 'Mac',
        price: 16599,
        quantity: 1,
    },
    {
        id: 17,
        img: 'img/produtos/mac-studio.webp',
        nome: 'Mac Studio',
        descrcao: 'teste',
        category: 'Mac',
        price: 22999,
        quantity: 1,
    },
    {
        id: 18,
        img: 'img/produtos/mac-mini.webp',
        nome: 'Mac mini',
        descrcao: 'teste',
        category: 'Mac',
        price: 7499,
        quantity: 1,
    },
    {
        id: 19,
        img: 'img/produtos/imac.webp',
        nome: 'iMac',
        descrcao: 'teste',
        category: 'Mac',
        price: 14499,
        quantity: 1,
    },
    {
        id: 20,
        img: 'img/produtos/macbookpro.webp',
        nome: 'MacBook Pro 14 pol.',
        descrcao: 'teste',
        category: 'Mac',
        price: 18499,
        quantity: 1,
    },
    {
        id: 21,
        img: 'img/produtos/macbook-air.webp',
        nome: 'MacBook Air 13 pol. com chip M2',
        descrcao: 'teste',
        category: 'Mac',
        price: 12499,
        quantity: 1,
    },
    {
        id: 22,
        img: 'img/produtos/macbook-air-20.webp',
        nome: 'MacBook Air 13 pol. com chip M1',
        descrcao: 'teste',
        category: 'Mac',
        price: 11599,
        quantity: 1,
    },
]

export { produtos };